### ISSUE TITLE
上传相同类型文件会返回同一个hash

### ISSUE THREAD

**Issue by jingqianwei** [Dianwoung/large-file-upload#1]
我第一次上传了一个test.txt文件上传成功了，后面又上传一个test1.txt文件且内容不相同，上传成功了但是找不到这个文件，我在本地测试发现这两个文件返回了同一个md5_file()的hash值，最后被你的程序识别成了同一个文件，程序如下
public function renameTempFile()
    {
        $savedFileHash = $this->generateSavedFileHash($this->uploadPartialFile);

        if ( RedisHandler::hashExists($savedFileHash) ) {
            $this->savedPath = RedisHandler::getFilePathByHash($savedFileHash);
        } else {
            $this->savedPath = ConfigMapper::get('FILE_DIR') . DIRECTORY_SEPARATOR . ConfigMapper::get('FILE_SUB_DIR') . DIRECTORY_SEPARATOR . $savedFileHash . '.' . $this->uploadExt;

            if ( ! @rename($this->uploadPartialFile, ConfigMapper::get('UPLOAD_PATH') . DIRECTORY_SEPARATOR . $this->savedPath) ) {
                return false;
            }
        }

        return $this->savedPath;
    }

**Comment by Dianwoung** [comment]
未能复现你的情况，上传的文件是同样的文件名和扩展名时，会发生覆盖现象。我在同一个表单两个字段，分别上传test1.txt和test2.txt，内容分别是123和456，检查未发现覆盖。

**Comment by DianWoung** [comment]
> 我第一次上传了一个test.txt文件上传成功了，后面又上传一个test1.txt文件且内容不相同，上传成功了但是找不到这个文件，我在本地测试发现这两个文件返回了同一个md5_file()的hash值，最后被你的程序识别成了同一个文件，程序如下
> public function renameTempFile()
> {
> $savedFileHash = $this->generateSavedFileHash($this->uploadPartialFile);
> 
> ```
>     if ( RedisHandler::hashExists($savedFileHash) ) {
>         $this->savedPath = RedisHandler::getFilePathByHash($savedFileHash);
>     } else {
>         $this->savedPath = ConfigMapper::get('FILE_DIR') . DIRECTORY_SEPARATOR . ConfigMapper::get('FILE_SUB_DIR') . DIRECTORY_SEPARATOR . $savedFileHash . '.' . $this->uploadExt;
> 
>         if ( ! @rename($this->uploadPartialFile, ConfigMapper::get('UPLOAD_PATH') . DIRECTORY_SEPARATOR . $this->savedPath) ) {
>             return false;
>         }
>     }
> 
>     return $this->savedPath;
> }
> ```
未能复现你的情况，上传的文件是同样的文件名和扩展名时，会发生覆盖现象。我在同一个表单两个字段，分别上传test1.txt和test2.txt，内容分别是123和456，检查未发现覆盖。
