### ISSUE TITLE
升级到 0.0.3以后上传失败

### ISSUE THREAD

**Issue by phpLHT** [Dianwoung/large-file-upload#11]
将"peinhu/aetherupload-laravel": "^2.0",升级了，上传文件报错。
setGroup方法不存在
\Encore\LargeFileUpload\LargeFileField::class 文件下
$('#{$name}-resource').change(function(){
          aetherupload('{$name}', this).setGroup('{$this->group}').setSavedPathField('#{$name}-savedpath').setPreprocessRoute('/aetherupload/preprocess').setUploadingRoute('/aetherupload/uploading').setLaxMode(false).success().upload('{$name}')
 });  这里调用的方法不存在；
public/vender/laravel-admin-ext/large-file-upload/js/aetherupload.admin.js  下未找到对应的方法

**Comment by DianWoung** [comment]
@phpLHT 原来的public下对应扩展包文件删掉，重新执行
````
php artisan vendor:publish --tag=large-file-upload
````
