### ISSUE TITLE
上传之后的文件使用 _ 分隔而不是 / 分隔

### ISSUE THREAD

**Issue by seth-shi** [Dianwoung/large-file-upload#13]
laravel 5.5
encore/laravel-admin 1.7.5,
显示的时候是需要自己手动替换字符吗？

**Comment by datangkang123** [comment]
碰到一样的问题，还有秒传无法实现。

**Comment by datangkang123** [comment]
在model中定义访问器，已解决了这问题：
` public function geturlAttribute($value)
    {
        return url('storage/'.str_replace('_','/',$value));//替换_为/并用url生成完整网址
    }`
具体使用记录：[我的博客](https://blog.dzbfsj.com/blog/15)

**Comment by asjianghang123** [comment]
请问哪个版本是 存储的数据库url    是 /  而不是 _

**Comment by asjianghang123** [comment]
![image](https://user-images.githubusercontent.com/45376471/67198493-a9bfb980-f431-11e9-91f0-4b6254527bfe.png)
您好.这边 是哪里出错了/ 有空希望能给我解答一下. 谢谢!!

**Comment by datangkang123** [comment]
@asjianghang123 
url是我的数据库用来存储文件链接的字段，需要改成您的字段名。

**Comment by asjianghang123** [comment]
在哪里改这个 东西呢。 我找了很久没找到设置uurl 路径的地方。您那边方便截个图吗。我是新手，刚
工作不到大半年。

**Comment by datangkang123** [comment]
laravel的model模型啊，我的博客里写的很清楚了。

**Comment by asjianghang123** [comment]
![image](https://user-images.githubusercontent.com/45376471/67207212-aa624b00-f445-11e9-8010-6a4d58a7d48a.png)
这个是我模型。 您看那个就是 那个代码。我试了没用。是有别的地方问题。我没处理吗

**Comment by datangkang123** [comment]
您的数据库，存储文件路径的字段名，是url吗？还是别的名称，要对应。
![ss](https://user-images.githubusercontent.com/46732047/67207337-f2816d80-f445-11e9-97e1-1d6d690b096e.png)

**Comment by asjianghang123** [comment]
方便加个微信吗/ 我搞这个东西都两天了。18015395534

**Comment by datangkang123** [comment]
13767725409
&nbsp;




康志华
职员
于都教育


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "asjianghang123"<notifications@github.com&gt;; 
发送时间: 2019年10月21日(星期一) 晚上9:01
收件人: "laravel-admin-extensions/large-file-upload"<large-file-upload@noreply.github.com&gt;; 
抄送: "康志华"<2554509967@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [laravel-admin-extensions/large-file-upload] 上传之后的文件使用 _ 分隔而不是 / 分隔 (#13)




方便加个微信吗/ 我搞这个东西都两天了。
