### ISSUE TITLE
与hasMany的综合使用不成功

### ISSUE THREAD

**Issue by jimyanghaodong** [Dianwoung/large-file-upload#14]
把方法放到hasMany的方法中之后方法使用不成功

**Comment by DianWoung** [comment]
> 把方法放到hasMany的方法中之后方法使用不成功

休假看看，工作日比较忙

**Comment by jimyanghaodong** [comment]
谢谢您




------------------ 原始邮件 ------------------
发件人: "DianWoung"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 晚上10:27
收件人: "laravel-admin-extensions/large-file-upload"<large-file-upload@noreply.github.com>; 
抄送: "东О"<996903585@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [laravel-admin-extensions/large-file-upload] 与hasMany的综合使用不成功 (#14)



 
把方法放到hasMany的方法中之后方法使用不成功
  
休假看看，工作日比较忙
 
- 
您收到此消息是因为您创作了该帖子。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by yk19** [comment]
请问这个问题解决了吗

**Comment by ahu** [comment]
这个问题难道没有解决？现在仍然有！

**Comment by ahu** [comment]
今天测试发现，composer require 安装的实际上是 2.0 分支，和 master 版本不一致。
不过虽然 master 版本时间线里有修复 hasMany 字样，但实测发现还是不行。看来的确是已经被放弃了...

**Comment by DianWoung** [comment]
> 今天测试发现，composer require 安装的实际上是 2.0 分支，和 master 版本不一致。 不过虽然 master 版本时间线里有修复 hasMany 字样，但实测发现还是不行。看来的确是已经被放弃了...

可以fork一份自行修改，我转golang了，没有时间搞这些了
