### ISSUE TITLE
better generate html by using view()

### ISSUE THREAD

**Issue by xiaohuilam** [Dianwoung/large-file-upload#2]
https://github.com/laravel-admin-extensions/large-file-upload/blob/e3e5cd7ee5d3101c9deedb28d4936f5ed7bf3b23/src/LargeFileField.php#L15-L22

I think, generate html from view is better

**Comment by DianWoung** [comment]
谢谢指导。因为依赖的项目Aether-upload已经升级2.0，本项目会在后面进行更新。
